* kb guix channel

Personal collection of [[https://guix.gnu.org/][GNU Guix]] package definitions.  Refer to the [[https://guix.gnu.org/manual/en/html_node/Channels.html/][manual]] for
more information on [[https://guix.gnu.org/manual/en/html_node/Channels.html][Guix Channels]].

*Disclaimer*: Packages found here may be upstreamed into the standard [[https://guix.gnu.org/][GNU Guix]]
channel and subsequently removed.

** Channel Introduction

Feel free to add the following to your channels list.

#+begin_src scheme
(channel
 (name 'kbg)
 (url "https://git.sr.ht/~kennyballou/guix-channel.git")
 (branch "master")
 (commit
  "69b39e045639354606dbb665a1957213e829391f")
 (introduction
  (make-channel-introduction
   "b9d0b8041d28ebd9f85cb041aa3f2235c8b39417"
   (openpgp-fingerprint
    "10F4 14AB D526 0D0E 2372  8C08 FE55 890B 57AE DCE5"))))
#+end_src

** Packages

*** nix-direnv

*** coq-math-classes

*** gnuplot-colorbrewer

*** gwl (git reference)

*** Emacs Packages

**** awqat

**** bibtex-to-plain-text

**** pulsar.el

**** elgantt

** License

The package definitions found in this channel are free software,
redistributable and modifiable under the terms and conditions of the GNU
General Public License as published by the Free Software Foundation, either
version 3, or (at your option) any later version.

You should have received a copy of the GNU General Public License with this
channel.  If not, see [[https://www.gnu.org/licenses/gpl-3.0.html]].

See [[./license][LICENSE]] for details.
