(define-module (guix check-packages))
;;; Loads the package modules into the Guix REPL to check all package variables

(use-modules (kbg packages aspell))
(use-modules (kbg packages coq-xyz))
(use-modules (kbg packages crates-io))
(use-modules (kbg packages crates-windows))
(use-modules (kbg packages emacs-xyz))
(use-modules (kbg packages fonts))
(use-modules (kbg packages gnuplot))
(use-modules (kbg packages golang-xyz))
(use-modules (kbg packages gwl))
(use-modules (kbg packages jdtls))
(use-modules (kbg packages languagetool))
(use-modules (kbg packages ltex-ls))
(use-modules (kbg packages networking))
(use-modules (kbg packages nix-xyz))
(use-modules (kbg packages node-xyz))
(use-modules (kbg packages nyxt-extensions))
(use-modules (kbg packages python-xyz))
(use-modules (kbg packages tex))
