---
name: Build packages

on:
  schedule:
    - cron: '51 17 * * *'
  push:
    branches: '*'
  pull_request:
    branches:
      - $default-branch

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      NO_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - name: Guix Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/guix
          key: guix-cache-${{ github.sha }}
          restore-keys: |
            guix-cache-
      - name: Install Guix
        uses: PromyLOPh/guix-install-action@v1
        with:
          channels: |-
            (list
             (channel
              (name 'guix)
              (url "https://codeberg.org/guix/guix")
              (introduction
               (make-channel-introduction
                "9edb3f66fd807b096b48283debdcddccfea34bad"
                 (openpgp-fingerprint
                  "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA")))))
      - name: Ensure no locale warning
        run: test -z "$(guix --version 2>&1 >/dev/null)"
      - name: Build/Verify Package
        run: |
          guix repl --load-path=./ guix/check-packages.scm
